version: "3.3"

services:
  store:
    image: store
    build: 
      context: store_service/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: store
    environment:
      - SERVER_ADDRESS=0.0.0.0:5001
      - PORT=5001
      - CONTEXT_TIMEOUT=30
      - DB_NAME=storage_management
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=mariadb
      - DB_PORT=3306
      - LOG_LEVEL=warning
      - STORAGE_PATH=store/
      - MAX_STORAGE_SIZE=300
      - MAX_FILE_SIZE=10
    ports:
      - "5001:5001"
    depends_on:
      - mariadb
  
  retreival:
    image: retreival
    build: 
      context: retrieval_service/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: retreival
    environment:
      - SERVER_ADDRESS=0.0.0.0:5000
      - PORT=5000
      - CONTEXT_TIMEOUT=2
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=user_management
      - ACCESS_TOKEN_EXPIRY_HOUR=2
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - ACCESS_TOKEN_SECRET=access_token_secret
      - REFRESH_TOKEN_SECRET=refresh_token_secret
      - LOG_LEVEL=info
      - STORE_SERVICE_HOST=store
      - STORE_SERVICE_PORT=5001
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
      - store
   
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: storage_management
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      # MYSQL_PORT: 3306
      # MARIADB_HOST: 0.0.0.0
    ports:
      - "3306:3306"
  
